server:
  port: 8080 # Cổng mặc định của Backend

manga:
  app:
    jwtSecret: NGVwYjN6YzhxMnB4OXU1aWp2bThkaWZrNnBoMmduOHltdmwycTM4ajYxazA # ${JWT_SECRET}
    jwtExpirationMs: 86400000
    googleClientId: 351530225339-5iq6pdi3mdt1fjje0krodp07e18jmi19.apps.googleusercontent.com # ${GOOGLE_CLIENT_ID}

cloudinary:
  cloud-name: dt1stlhqc # ${CLOUDINARY_CLOUD_NAME}
  api-key: 912788441748564 # ${CLOUDINARY_API_KEY}
  api-secret: dmTXCWvYWMKHZgsQPvirbywk8Ps # ${CLOUDINARY_API_SECRET}

spring:
  datasource:
    # Đường link kết nối trực tiếp đến máy chủ Supabase
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.qtmrecvimbofafyfesjg&password=n8fQh$-e7ELAwX$
    username: postgres.qtmrecvimbofafyfesjg
    password: n8fQh$-e7ELAwX$
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5    # Chỉ cho phép tối đa 5 kết nối đồng thời (Nhỏ hơn giới hạn 15 của Supabase)
      minimum-idle: 1         # Chỉ giữ 1 kết nối chạy ngầm khi không có ai dùng
      idle-timeout: 300000    # Đóng kết nối nếu không dùng sau 5 phút (300,000 ms)
      connection-timeout: 20000 # Thời gian chờ tối đa để lấy kết nối là 20s
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Ép Hibernate chuyển sang nói ngôn ngữ PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true

  mail:
    host: smtp.gmail.com
    port: 587
    username: lehoangem06092006 # ${MAIL_USERNAME}
    password: qpjn foac zvqn goma # ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Cấu hình giới hạn dung lượng file upload (Cho tính năng Upload trang truyện Manga)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB